### ISSUE TITLE
Attachements (picture upload) No pictures will be show in Editor

### ISSUE THREAD

**Issue by neckflo** [martec/Rin-Editor_for_phpBB#14]
Problem: No pictures will be showed with the "Attachements" funcion.

If i upload some new photos with attachements. The pictues will not show in the post.
If i push to "This attachement show in post" no function. The pictures will be deleted.

Maybe you can help. Thank you

**Comment by martec** [comment]
Can you explain with the screenshot?
Because I tried reproduce here, and I did not succeed.

**Comment by neckflo** [comment]
If i have upload the picutre i want to add the picture to the post. Nothing happend.
In the preview the picture will be lost.

In the old editor the upload works very well.

https://www.pic-upload.de/view-33451343/1.png.html

**Comment by martec** [comment]
Thanks for reprort. I will fix in next version.

**Comment by martec** [comment]
done.

**Comment by neckflo** [comment]
Thank you very much!
