### ISSUE TITLE
geting a SQL ERROR ones i tern this mod on when on a forum page where the Editor should be 

### ISSUE THREAD

**Issue by raykai** [martec/Rin-Editor_for_phpBB#15]
Hi i just got a  SQL ERROR ones i turned this mod [3.2][BETA] on when on a forum page where the Editor should be 
i don't get this error when i turn off the mod.

![general error](https://user-images.githubusercontent.com/8138894/29301582-3da1f8cc-814b-11e7-9555-65b7b205050f.png)

im running on:
OVH VPS
2g ram 
OS: ‪Ubuntu 16.04.3 LTS‬
Product: Plesk Onyx 17.5.3 Update #18 
MySQL Version: 5.7.19
PHP Version: 7.1.8

-------------------------------
General Error
SQL ERROR [ mysqli ]

Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'live_aquaexotik_forum_phpbb.phpbb_smilies.code' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by [1055]

SQL

SELECT smiley_url, code, display_on_posting, emotion FROM phpbb_smilies GROUP BY smiley_url

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 999
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/ext/rin/editor/event/main_listener.php
LINE: 302
CALL: phpbb\db\driver\factory->sql_query()

FILE: (not given by php)
LINE: (not given by php)
CALL: rin\editor\event\main_listener->initialize_rceditor()

FILE: [ROOT]/vendor/symfony/event-dispatcher/EventDispatcher.php
LINE: 184
CALL: call_user_func()

FILE: [ROOT]/vendor/symfony/event-dispatcher/EventDispatcher.php
LINE: 46
CALL: Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 60
CALL: Symfony\Component\EventDispatcher\EventDispatcher->dispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 46
CALL: phpbb\event\dispatcher->dispatch()

FILE: [ROOT]/viewtopic.php
LINE: 2287
CALL: phpbb\event\dispatcher->trigger_event()

**Comment by martec** [comment]
Hi...

try made edit below.

open root/ext/rin/editor/event/main_listener.php
find:

`		$sql = 'SELECT smiley_url, code, display_on_posting, emotion
			FROM ' . SMILIES_TABLE . '
			GROUP BY smiley_url';`

replace:

`		$sql = 'SELECT smiley_url, code, display_on_posting, emotion
			FROM ' . SMILIES_TABLE . '';`

**Comment by raykai** [comment]
il try this tonight, il let you know if it works or not.

**Comment by raykai** [comment]
yes, this seems to fix the prob :) hope to see this fix in your next release.

i also wanted to say a big thank you for doing this mod it was really needed on phpbb.

i just hope you will maintain this mod for a very-long time. :) 
it is so useful for users than the confusing bbcode.

**Comment by martec** [comment]
Hi,

thanks for to confirm that fix work.
I need to do some testing locally before applying the fix.

**Comment by martec** [comment]
i will fix in next version.
so closed.
