### ISSUE TITLE
cant remove BBcode permission from evryone

### ISSUE THREAD

**Issue by raykai** [martec/Rin-Editor_for_phpBB#16]
Hi,
I cant seem to remove all rights to bbcodes i have unblued (unselected) all groups from the Group permission on the box just under the Choice BBcode box then i save (submit) but it still keeps the permissions that were selected last time.

No way to fully remove all permission even to admins. hope there will be a way to do this.

![bugg](https://user-images.githubusercontent.com/8138894/29393816-2bed3080-82d4-11e7-9de3-e63139d5c77b.JPG)

**Comment by martec** [comment]
Hi,

remove permission for all for now does not possible.
You can remove bbcode from acp, which results in the same thing.
