### ISSUE TITLE
a way to resize images when using the Image button.

### ISSUE THREAD

**Issue by raykai** [martec/Rin-Editor_for_phpBB#17]
Hi,

It would be nice having a way to resize the images when using the Image button. there is no size option only a URL and Preview window. one's users post an image in the editor. there is no way to drag size the images.

Having those option would be nice to have.

Thx for your hard work.

**Comment by raykai** [comment]
An other option that would be nice to have is a button for the users to switch the editor back to the default one. some times users need to enter bbcodes or some just likes the default phpbb editor.

So having a switch button in or under your editor for switching the editor would be nice.

**Comment by martec** [comment]
Sorry, but the bbcode image tag of phpBB does not accept size attribuition.
