### ISSUE TITLE
align bbcodes probs

### ISSUE THREAD

**Issue by raykai** [martec/Rin-Editor_for_phpBB#18]
Hi,
just wondering why you use the bbcodes  [align=left] [align=center] [align=right] [align=justify]

Most would use the normal bbcodes [left] [center] [right] [justify].

Also the bbcodes  [align=left] [align=center] [align=right] [align=justify] are not compatible with the tapatalk app [https://www.tapatalk.com/](https://www.tapatalk.com) that so many users use on there mobile platforms to look at forums.

**Comment by martec** [comment]
Hi,

not possible change, because this is directly associated with the extension permission system.
