### ISSUE TITLE
js error "quick_quote is not defined"

### ISSUE THREAD

**Issue by 7starsone** [martec/Rin-Editor_for_phpBB#25]
Hello,
if quick quote is enabled, just when you browse a topic page, it returns this:

![quickquote](https://s10.postimg.org/xvtocdu8p/quickquote.jpg)

Why, please? 
Thanks

**Comment by 7starsone** [comment]
I'm on `viewtopic_body_postrow_post_details_before.html`

here I see:
```
{% if RCE_LOAD and RCE_QUICK_QUOTE %}
...
```
assuming that this syntax is correct,
here, quick quote is enabled ( I guess **RCE_QUICK_QUOTE** is set... ?)
but what's exactly the other and what should I see on the page?

**Comment by martec** [comment]
hi,

could you fix the link? for me not working.

**Comment by martec** [comment]
no reply so closed. create again if yet need support.

**Comment by martec** [comment]
i see the error.
i will fix in next version.
