### ISSUE TITLE
PAGE_NOT_FOUND

### ISSUE THREAD

**Issue by brf86** [martec/Rin-Editor_for_phpBB#27]
Hello! When I try to send something in Source Mode, phpBB returns the follow message:

"Information

PAGE_NOT_FOUND"

Then when sending on WYSIWSG mode, it works. Any ideas?

**Comment by martec** [comment]
Could you provide more details?
OS (windows, android etc...), brownser (FF, Chrome etc...), which page this happen (new post, new thread, PM etc...)

**Comment by martec** [comment]
no detail, so closed.
