### ISSUE TITLE
breaks official Imgur extn

### ISSUE THREAD

**Issue by mhudson324** [martec/Rin-Editor_for_phpBB#28]
Breaks existing imgur mod[https://www.phpbb.com/customise/db/extension/imgur/]( https://www.phpbb.com/customise/db/extension/imgur)/
 with no option to disable the rin-editors own implementation.

Rin-Editor does not have the same options the approved imgur app such as client secret, album folder selection and pin.

An option to disable rin-imgur from the acp would be ideal (or remove it completely as there is an approved imgur ext)

**Comment by martec** [comment]
Hi,

Sorry but I can not do anything about it.
This extension you are indicating does not support my extension.
So it will never work with my extension, unless the extension's developer makes it compatible with my extension.
