### ISSUE TITLE
Simple mentions + [code] + Paragraph = Bug

### ISSUE THREAD

**Issue by JuniorDjjr** [martec/Rin-Editor_for_phpBB#34]
https://youtu.be/gKAlw4gwyUY

This has already disturbed me a lot and I have lost entire texts because of this, today I was able to understand and reproduce the bug.
Apparently a character `@` in a `[code]` causes a bug in the rest of the topic after clicking a new paragraph created bellow another `[code]`.

**Comment by martec** [comment]
sorry this isn't has solution. the mention extension use the At.js library that was abandoned. https://github.com/ichord/At.js/
