### ISSUE TITLE
How to have the visual in the editor when we create a personalized bbcode ?

### ISSUE THREAD

**Issue by association-amis** [martec/Rin-Editor_for_phpBB#35]
Hello Martec,

Great job for this add-on ... a big thank you ...
 
I have a little question :

How to have the visual and not the code, in the editor, when we create a personalized  bbcode?

Let me explain :"
1- I created the bbcode highlight to highlight the text in yellow and added a .png icon here / ext / rin / editor / styles / all / template / js / icons /
=> It is perfectly operational ...

2- I find the icon in the bar custom bbcodes ...
=> Everything seems OK

But when I want to use it, in the editor is the bbcode tag that appears and not the visual ...
If I view the message, the characters are highlighted ...

Thank you in advance for your answer

Have a good day
Sincerely,
Pierre BOULANGER

**Comment by TassLehoff** [comment]
I have the same problem, there is no visual editor for every button i add.

I use phpBB 3.2.2

**Comment by martec** [comment]
sorry this editor doesn't support something like.
you need create plugin to do something like.
