### ISSUE TITLE
this extension is abandoned?

### ISSUE THREAD

**Issue by meis2m** [martec/Rin-Editor_for_phpBB#39]
Hello any update ?
is abandoned?

**Comment by Galixte** [comment]
Hi @martec,

could you answer, please?

Regards.

**Comment by martec** [comment]
This isn't abandoned.

**Comment by martec** [comment]
check here https://github.com/martec/Rin-Editor_for_phpBB/releases new version released today.

**Comment by Galixte** [comment]
Τhanks!
