### ISSUE TITLE
Simple Mentions mentions aren't WYSIWYG?

### ISSUE THREAD

**Issue by burner1024** [martec/Rin-Editor_for_phpBB#46]
The mentions are displayed as bbcode instead of proper "@username":

![Captura de pantalla de 2020-03-17 20-20-32](https://user-images.githubusercontent.com/1279852/76859981-dcf56000-688c-11ea-91e7-0976c920864e.png)

![Captura de pantalla de 2020-03-17 20-20-44](https://user-images.githubusercontent.com/1279852/76859986-de268d00-688c-11ea-9e20-33b5aab0d30c.png)

Is it supposed to be this way?

**Comment by martec** [comment]
yes.
