### ISSUE TITLE
MChat Error

### ISSUE THREAD

**Issue by miri4ever** [martec/Rin-Editor_for_phpBB#47]
I got the following Error inside Editor Console after try to open MCha inside a new windows and cant edit anyhing inside of it. Calling the function from INDEX Page direcly it works fine, but calling from a new open exta Site gives me this errors.

ckeditor.js?assets_version=6522:574 Uncaught TypeError: m[f].replace is not a function
    at ckeditor.js?assets_version=6522:574
    at ckeditor.js?assets_version=6522:608
    at ckeditor.js?assets_version=6522:1018
(anonymous) @ ckeditor.js?assets_version=6522:574
(anonymous) @ ckeditor.js?assets_version=6522:608
(anonymous) @ ckeditor.js?assets_version=6522:1018
ckeditor.js?assets_version=6522:251 Uncaught TypeError: Cannot read property 'replace' of undefined
    at n (ckeditor.js?assets_version=6522:251)
    at ckeditor.js?assets_version=6522:250
    at ckeditor.js?assets_version=6522:476
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.resourceManager.<anonymous> (ckeditor.js?assets_version=6522:239)
    at g (ckeditor.js?assets_version=6522:234)
    at Array.n (ckeditor.js?assets_version=6522:234)
    at v (ckeditor.js?assets_version=6522:235)
    at ckeditor.js?assets_version=6522:235

**Comment by martec** [comment]
hi 

this editor doesn't work with mchat..
offer for me link for "new open exta Site", to avoid load this editor when you using mchat.

**Comment by miri4ever** [comment]
You mean a link to mcat running on my page ?

The funny thing it works from INDEX without trouble. But extra site or Portal Module giving me this error only if open console of browser. In real I did not see anything on screen only that I can not place my cursor inside the chat field. Something from the BBCodes or Input must call a routine from the editor even if not used in the chat.

**Comment by martec** [comment]
>You mean a link to mcat running on my page ?

yes, of course, you can hide domain part of link.

**Comment by miri4ever** [comment]
I have an update on this as well:

I don't know if you have MChat going on and your editor. As soon as you start the chat via external page or via the portal, you cannot position the input cursor in the text field anymore.

What have now so far the following found out: Blame for this thing is first:

Enable URL rewriting:
If activated, URLs containing 'app.php' will be rewritten so that they don't contain a file name anymore. (for example, app.php/foo becomes /foo). The Apache web server's mod_rewrite module is necessary for this to work. If this option is enabled without mod_rewrite being available, URLs on your board may become invalid.

If you turn this off in the settings, the chat will not cause any problems with the external site, but it will lack many features. On the portal it still doesn't work.

In any case, it doesn't have to be compatible with the URL rewrite functions that cause the error codes posted above.

**Comment by martec** [comment]
hi,

the editor check  if url has word "index.php or mchat or chat" to avoid load.
https://github.com/martec/Rin-Editor_for_phpBB/blob/master/rin/editor/event/main_listener.php#L185

if your custom url has other word so you need add manually.

**Comment by miri4ever** [comment]
Hello,

thanks for your support and it looks like you pointed me to the right direction and after a few tries with mod url rewrite problems I sorted now all problems out and all chat and external links with app.php now working fine, after doing this kind of fix

		if (((!$this->config['RCE_enb_quick'] || !$this->config['allow_quick_reply']) && $eventname == 'core.viewtopic_modify_page_title') || ($rceurl == 'index.php' || $rceurl == 'app.php' || $rceurl == 'mchat' || $rceurl == 'portal' || $rceurl == 'chat'))

adding portal and app.php as the trouble makers to the list and all now working fine. Maybe those could be inside next release so others maybe with same problems could have a working solution too for this.


Thanks very much and kisses :)

**Comment by martec** [comment]
hi,

thanks...
if i release a new version in the future, i will add this
