### ISSUE TITLE
Permssions / BBCode not allowed

### ISSUE THREAD

**Issue by miri4ever** [martec/Rin-Editor_for_phpBB#48]
It can setup permissions for Adims and others for each BBCode. If all fields are unchecked it works fine and I can use all BBCode. 

But if I now maybe allow a special BBCode for Admins only, the editor tells me I am not allowed to use this code, even if I selected ADMIN for example. I selected other Users, and selected anything I got to allow this BBCode. All the same result: You are not allowed to use. 

Only after I uncheck all permissions to normal it works again. As soon as one no matter what group selected I could not use anymore this code. It seems it sure checks this code is not allowed, but somehow it ignores the permssion is set for this type of User I want. 

Can anyone confirm this ?

**Comment by martec** [comment]
for me work fine in test forum.
if i select only admin, so only admin can use. If i select only "users", so only users can use.
i don't know what version of phpbb are you using, but the last version of this tested only with 3.2.5.

**Comment by miri4ever** [comment]
Yes, the error is mean to find and I strangely enough ran now everything well 7 weeks with all settings top. Until yesterday:

I wanted to insert a new BBCode and then I got the message "I am not allowed to use it" when I posted it. For the new BBCode there were no permissions set and it didn't want to run. 

Everything else went fine.

Then I switched off all extensions for a PHPBB 3.3.1 update for security reasons and then switched them all on again. And see because all BBCodes with permissions failed from this point on again !

Until I reseted everything without considerations it ran again except for the new BBCode which just didn't want it.

Since it works for you and has worked for me also 2 weeks, I now went on the troubleshooting. State of things so far:


Ultimate Points Extension / dmzx/ultimatepoints

seems to cause these errors. If I disable it, the new BBCode will also run with and without permissions. Since I've been using this extension for a long time and it worked for 2 weeks when both were active, I can't say what the problem is now. I am currently switching them both on and off to see where the error could be, I got that already 1x.

Maybe you can do some tests from your side to see how far it interferes with the permissions of the editor.

**Comment by martec** [comment]
Hi

i tested with new version of phpbb and work fine for me.... And today i released new version.
I didn't try with the mentioned plugin, as I won't be able to do anything about the third-party plugin.

so i will close this issue...
