### ISSUE TITLE
Please add support for mchat/ajaxchat

### ISSUE THREAD

**Issue by maras26** [martec/Rin-Editor_for_phpBB#5]

**Comment by martec** [comment]
I already answered here https://www.phpbb.com/community/viewtopic.php?f=456&t=2427126&start=30#p14763566

**Comment by martec** [comment]
Sorry, I tried but it's more complicated than I imagined. And to make matters worse, the editor conflicts with mchat. In which the conflict itself will be solved, but adding the editor in mchat and ajaxchat will not be possible.
