### ISSUE TITLE
Quick Quote malfunctions with HTML entities

### ISSUE THREAD

**Issue by Kenifornication** [martec/Rin-Editor_for_phpBB#51]
Hello,

I've been using your editor for a while and it's been great so far, thank you!

We're having a little problem with the Quick Quote feature, wherein it kind of breaks down with posts containing HTML reserved characters like "&<>, and replaces them with literal HTML entities like `&quot;` and `&amp;`

So, basically if someone posts `Man Utd >>>>>>>>>>> Man City` and I Quick Quote it, it would show `Man Utd &gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt; Man City`, and if someone quotes my reply it would become even more of a monstrosity `Man Utd &amp;gt;&amp;gt;&amp;gt;&amp;gt;&amp;gt;&amp;gt;&amp;gt; Man City`

I thought about disabling the feature but my users love it and there's no getting that cat back into the bag now. Could you please look into it?

**Comment by martec** [comment]
Hi,

are you saying about quick reply feature?
because for me quick quote doesn't has this issue for me.
I'll try to fix issue in quick reply, but I can't guarantee.

**Comment by Kenifornication** [comment]
Yes, this is with the "Quick Reply feature" enabled
Here are my settings if that helps:

![settings](https://user-images.githubusercontent.com/12016198/117672955-d9f8b580-b199-11eb-8303-786745f85192.png)

**Comment by martec** [comment]
fixed in 0.4.2.
thanks for report!

**Comment by Kenifornication** [comment]
Hello again,

While the update fixed the html entities problem (thank you very much!), it introduced a new problem where newlines are not handled properly (multiline text is quoted as one line). Could you look into it, please?

Thank you

**Comment by martec** [comment]
sorry for inconvenience.
fixed in 0.4.3.
thanks for report!

**Comment by Kenifornication** [comment]
Just reporting back to say that it works as expected now. Thank you very much for the quick update.

**Comment by martec** [comment]
Thanks for feedback!
I'm glad the solution worked.
